### ISSUE TITLE
EPIC: Move from cypres to console-test

### ISSUE THREAD

**Issue by ben-vegaprotocol** [vegaprotocol/console-test#12]
Move current cypress tests into console-test:

```[tasklist]
### Test files to be converted
- [ ] TS assets.cy.ts
- [ ] TS capsule.cy.ts
- [ ] TS charts-depth.cy.ts
- [ ] TS closed-markets.cy.ts
- [ ] TS deposit.cy.ts
- [ ] TS home-node-network.cy.ts
- [ ] TS home.cy.ts
- [ ] TS live-env.cy.ts
- [ ] TS market-all.cy.ts
- [ ] TS market-info.cy.ts
- [ ] TS market-liquidity.cy.ts
- [ ] TS market-proposal-notification.cy.ts
- [ ] TS market-selector.cy.ts
- [ ] TS market-split-bottom-panels.cy.ts
- [ ] TS market-summary.cy.ts
- [ ] TS markets-proposed.cy.ts
- [ ] TS markets.cy.ts
- [ ] TS navbar.cy.ts
- [ ] TS oracle.cy.ts
- [ ] TS order-book.cy.ts
- [ ] TS settings.cy.ts
- [ ] TS trading-accounts.cy.ts
- [ ] TS trading-chart.cy.ts
- [ ] TS trading-deal-ticket-basic-submit.cy.ts
- [ ] TS trading-deal-ticket-basics.cy.ts
- [ ] TS trading-deal-ticket-order.cy.ts
- [ ] TS trading-deal-ticket-submit-account.cy.ts
- [ ] TS trading-deal-ticket-submit-batch-auction.cy.ts
- [ ] TS trading-deal-ticket-submit-monitoring-auction.cy.ts
- [ ] TS trading-deal-ticket-submit-opening-auction.cy.ts
- [ ] TS trading-deal-ticket-submit-suspended.cy.ts
- [ ] TS trading-deal-ticket-time-in-force.cy.ts
- [ ] TS trading-fills.cy.ts
- [ ] TS trading-orders.cy.ts
- [ ] TS trading-portfolio.cy.ts
- [ ] TS trading-positions.cy.ts
- [ ] TS trading-trades.cy.ts
- [ ] TS wallet-eth.cy.ts
- [ ] TS wallet-vega.cy.ts
- [ ] TS withdraw-key-to-key.cy.ts
- [ ] TS withdraw.cy.ts
```

**Comment by bwallacee** [comment]
After moving off of cypress we want to evalute if running the full suite is viable:
https://github.com/vegaprotocol/console-test/issues/62
