### ISSUE TITLE
EPIC: Test coverage on features that market-sim unlocks

### ISSUE THREAD

**Issue by ben-vegaprotocol** [vegaprotocol/console-test#17]
## Overview

In order to gain the most value out of the new test framework utlising vega-market-sim. We want to create tests for the scenarios that are now possible.

For each of these features there must be specs created/ammended.

### Features
- [ ] Opening auction -> continuous trading
- [ ] Continuous trading -> price monitoring auction
- [ ] Continuous trading -> market expiry/settlement
  - Ledger entries
  - Accounts
- [ ] Trades matching (have a start on this already I believe)
  - Trades table
  - Fills table
  - Orders table
- [ ] Position opening (also started)
- [ ] Position closing
- [ ] Liquidity submission
- [ ] Deal ticket fees/estimations
- [ ] Market data updates
  - Market header
  - Market selector
  - Market table
