### ISSUE TITLE
EPIC: Poc vega sim tests

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/console-test#2]
## Overview

Iron out any teething issues with using vega-market-sim

## Tasks

- [x] Figure out how to set datanode url for app pulled from docker @mattrussell36 
  - Depends on https://github.com/vegaprotocol/frontend-monorepo/pull/4159
- [x] Get playwright report working @ben-vegaprotocol 
- [x] Set up traces @ben-vegaprotocol 
- [x] Set up parallelization @daro-maj 
- [x] How do we manage dependencies to ensure we have the right version of core (via vega-market-sim) _and_ the right version of the frontend.

## Tests

- Market state and trading mode transition @daro-maj 
  - [x] Specs updated
  - [x] Test added
- Trade history @radoslaw-szpiech 
  - [x] Specs updated
  - [x] Test added
- Order match and position creation @ben-vegaprotocol 
  - [x] Specs updated
  - [x] Test added

**Comment by ben-vegaprotocol** [comment]
Default playwright report doesn't work using python currently. We could use allure reporting or something simmilar but i think we skip for now.

**Comment by ben-vegaprotocol** [comment]
In terms of dependancy management.

For what version of console we run against we can control the container through CI and have tests running against different versions depending when and where we want.

In terms of the correct verszion of Vega, I have this response from Tom:

> Hey, if you're running via Jenkins then it should be possible to pass in the version of Vega which is used (depending on how exactly you're setting it up)
So we have a pipeline which runs market sim vs the latest Vega core version every time there is a merge to develop
And generally try to keep that green
Then we upgrade the version in the internal .env file when we need to/feel like it
