### ISSUE TITLE
e2e test for 24h volume change

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/console-test#55]
## Tasks

- [ ] Review test coverage (unit and e2e)
- [ ] Add applicable e2e tests
- [ ] Ensure biz logic around which candles are used for the values are unit tested

**Comment by mattrussell36** [comment]
Consider covering this with unit tests rather than e2e?

**Comment by bwallacee** [comment]
@mattrussell36 that makes sense, it's not a high risk area at all either, so I think a unit test and then if someone notices something we can fix forward etc.
